"""phase2_operations

Revision ID: 2e914ce099c4
Revises: 87dd3b95f9d7
Create Date: 2026-09-26 16:11:55.847702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e914ce099c4'
down_revision: Union[str, Sequence[str], None] = '87dd3b95f9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_alerts_alert_type'), 'operational_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_operational_alerts_created_at'), 'operational_alerts', ['created_at'], unique=False)
    op.create_index('ix_operational_alerts_org_ack', 'operational_alerts', ['organization_id', 'is_acknowledged'], unique=False)
    op.create_index(op.f('ix_operational_alerts_organization_id'), 'operational_alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_reference_id'), 'operational_alerts', ['reference_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_suppliers_org_code')
    )
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_number', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('system_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('physical_count', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'adjustment_number', name='uq_adjustments_org_number')
    )
    op.create_index(op.f('ix_adjustments_adjustment_number'), 'adjustments', ['adjustment_number'], unique=False)
    op.create_index(op.f('ix_adjustments_location_id'), 'adjustments', ['location_id'], unique=False)
    op.create_index(op.f('ix_adjustments_organization_id'), 'adjustments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_adjustments_product_id'), 'adjustments', ['product_id'], unique=False)
    op.create_index(op.f('ix_adjustments_status'), 'adjustments', ['status'], unique=False)
    op.create_index(op.f('ix_adjustments_warehouse_id'), 'adjustments', ['warehouse_id'], unique=False)
    op.create_table('delivery_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('delivery_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'delivery_number', name='uq_delivery_orders_org_number')
    )
    op.create_index(op.f('ix_delivery_orders_delivery_number'), 'delivery_orders', ['delivery_number'], unique=False)
    op.create_index(op.f('ix_delivery_orders_organization_id'), 'delivery_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_source_location_id'), 'delivery_orders', ['source_location_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_status'), 'delivery_orders', ['status'], unique=False)
    op.create_index(op.f('ix_delivery_orders_warehouse_id'), 'delivery_orders', ['warehouse_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'receipt_number', name='uq_receipts_org_number')
    )
    op.create_index(op.f('ix_receipts_destination_location_id'), 'receipts', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_receipts_organization_id'), 'receipts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_index(op.f('ix_receipts_supplier_id'), 'receipts', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_receipts_warehouse_id'), 'receipts', ['warehouse_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('source_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'transfer_number', name='uq_transfers_org_number')
    )
    op.create_index(op.f('ix_transfers_destination_location_id'), 'transfers', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_transfers_destination_warehouse_id'), 'transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfers_organization_id'), 'transfers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transfers_source_location_id'), 'transfers', ['source_location_id'], unique=False)
    op.create_index(op.f('ix_transfers_source_warehouse_id'), 'transfers', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_number'), 'transfers', ['transfer_number'], unique=False)
    op.create_table('delivery_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('picked_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('packed_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('delivered_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('delivered_quantity >= 0', name='ck_delivery_lines_delivered_pos'),
    sa.CheckConstraint('packed_quantity >= 0', name='ck_delivery_lines_packed_pos'),
    sa.CheckConstraint('picked_quantity >= 0', name='ck_delivery_lines_picked_pos'),
    sa.CheckConstraint('requested_quantity >= 0', name='ck_delivery_lines_requested_pos'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_delivery_lines_reserved_pos'),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_order_lines_delivery_id'), 'delivery_order_lines', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_order_lines_product_id'), 'delivery_order_lines', ['product_id'], unique=False)
    op.create_table('receipt_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('expected_quantity >= 0', name='ck_receipt_lines_expected_pos'),
    sa.CheckConstraint('received_quantity >= 0', name='ck_receipt_lines_received_pos'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_lines_product_id'), 'receipt_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_receipt_id'), 'receipt_lines', ['receipt_id'], unique=False)
    op.create_table('transfer_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_transfer_lines_quantity_pos'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_lines_product_id'), 'transfer_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_transfer_lines_transfer_id'), 'transfer_lines', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_lines_transfer_id'), table_name='transfer_lines')
    op.drop_index(op.f('ix_transfer_lines_product_id'), table_name='transfer_lines')
    op.drop_table('transfer_lines')
    op.drop_index(op.f('ix_receipt_lines_receipt_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_product_id'), table_name='receipt_lines')
    op.drop_table('receipt_lines')
    op.drop_index(op.f('ix_delivery_order_lines_product_id'), table_name='delivery_order_lines')
    op.drop_index(op.f('ix_delivery_order_lines_delivery_id'), table_name='delivery_order_lines')
    op.drop_table('delivery_order_lines')
    op.drop_index(op.f('ix_transfers_transfer_number'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_source_warehouse_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_source_location_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_organization_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_warehouse_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_location_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_receipts_warehouse_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_supplier_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_organization_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_destination_location_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_delivery_orders_warehouse_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_status'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_source_location_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_organization_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_delivery_number'), table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_index(op.f('ix_adjustments_warehouse_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_status'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_product_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_organization_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_location_id'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_adjustment_number'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_operational_alerts_reference_id'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_organization_id'), table_name='operational_alerts')
    op.drop_index('ix_operational_alerts_org_ack', table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_created_at'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_alert_type'), table_name='operational_alerts')
    op.drop_table('operational_alerts')
    # ### end Alembic commands ###
