"""Add ledger and audit

Revision ID: 87dd3b95f9d7
Revises: 52ca1ba9d884
Create Date: 2026-09-26 14:39:34.014545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87dd3b95f9d7'
down_revision: Union[str, Sequence[str], None] = '52ca1ba9d884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('stock_ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledger_entries_created_at'), 'stock_ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_location_id'), 'stock_ledger_entries', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_organization_id'), 'stock_ledger_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_product_id'), 'stock_ledger_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_reference_id'), 'stock_ledger_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entries_transaction_type'), 'stock_ledger_entries', ['transaction_type'], unique=False)
    op.create_index('ix_stock_ledger_org_prod_loc', 'stock_ledger_entries', ['organization_id', 'product_id', 'location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_ledger_org_prod_loc', table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_transaction_type'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_reference_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_product_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_organization_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_location_id'), table_name='stock_ledger_entries')
    op.drop_index(op.f('ix_stock_ledger_entries_created_at'), table_name='stock_ledger_entries')
    op.drop_table('stock_ledger_entries')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
